//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pracrica_Atelie.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public System.DateTime TimeOfOrder { get; set; }
        public System.DateTime EndTime { get; set; }
        public int IdEmployee { get; set; }
        public int IdClient { get; set; }
        public int IdTitleWork { get; set; }
        public int IdMaterials { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual TitleWork TitleWork { get; set; }
    }
}
