//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pracrica_Atelie.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int IdProducts { get; set; }
        public int IdMaterial { get; set; }
        public int Quantity { get; set; }
        public int IdProvide { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
